const test=require('node:test'),assert=require('node:assert/strict'),{randomUUID}=require('node:crypto');
const {validateEvent,updateDaily,updatePresence,listenerCount,summarize,createAudience}=require('../api/audience');
const now=Date.parse('2026-10-06T12:00:00Z'), visitorId=randomUUID(),tabId=randomUUID();
const event=(type='pageview',extra={})=>({visitorId,tabId,eventId:randomUUID(),type,...(type==='pageview'?{path:'/'}:{}),...extra});
test('strict public schema rejects sensitive fields and technical/admin routes',()=>{for(const path of ['/admin','/api/live','/login'])assert.throws(()=>validateEvent(event('pageview',{path})));assert.throws(()=>validateEvent(event('pageview',{email:'x'})));assert.throws(()=>validateEvent(event('pageview',{visitorId:'invalid'})));});
test('first visit, refresh and SPA route count views but deduplicate visitor',()=>{let d=updateDaily(null,event(),now).doc;d=updateDaily(d,event('pageview',{path:'/listen'}),now+6000).doc;assert.equal(d.visits,2);assert.equal(Object.keys(d.visitors).length,1);assert.equal(d.pages['/listen'],1);});
test('duplicate event and rapid React duplicate do not write aggregate',()=>{const e=event(),d=updateDaily(null,e,now).doc;assert.equal(updateDaily(d,e,now+9000).changed,false);assert.equal(updateDaily(d,event(),now+100).changed,false);});
test('play enters presence, pause/ended removes it',()=>{let d=updatePresence(null,event('audio_start'),now);assert.equal(listenerCount(d,now),1);d=updatePresence(d,event('stop'),now+1000);assert.equal(listenerCount(d,now+1000),0);});
test('expired abandoned session does not count',()=>{const d=updatePresence(null,event('audio_start'),now);assert.equal(listenerCount(d,now+120001),0);});
test('two tabs are one listener; stop only removes the tab that stopped',()=>{let d=updatePresence(null,event('audio_start'),now);const other=randomUUID();d=updatePresence(d,event('audio_start',{tabId:other}),now+1000);assert.equal(listenerCount(d,now+1000),1);d=updatePresence(d,event('stop'),now+2000);assert.equal(listenerCount(d,now+2000),1);});
test('refresh pagehide stop is consistent and playback must restart',()=>{let d=updatePresence(null,event('audio_start'),now);d=updatePresence(d,event('stop'),now+1000);assert.equal(listenerCount(d,now+2000),0);});
test('summary deduplicates visitor across days and never exposes identifiers',()=>{const d=updateDaily(null,event(),now).doc;const d2=updateDaily(null,event(),now-86400000).doc;const s=summarize([d,d2],now,0);assert.equal(s.visitors30,1);assert.equal(s.visits30,2);assert.ok(!JSON.stringify(s).includes(visitorId));assert.ok(!JSON.stringify(s).includes(Object.keys(d.visitors)[0]));});
function res(){return {code:0,set(){},status(c){this.code=c;return this;},json(v){this.body=v;return this;}};}
const req=(path,headers={},body)=>({path,method:body?'POST':'GET',body,get:k=>headers[k],is:()=>true});
test('private dashboard denies anonymous and wrong account before repository read',async()=>{let reads=0;const h=createAudience({repository:{dashboard:async()=>{reads++;return {};}},verifyIdToken:async()=>({uid:'wrong'}),getAdminUid:()=> 'admin'});for(const headers of [{},{Authorization:'Bearer fixture'}]){const r=res();await h(req('/api/admin/analytics',headers),r);assert.ok([401,403].includes(r.code));}assert.equal(reads,0);});
test('authorized dashboard allowed and public response contains only listener count',async()=>{const h=createAudience({repository:{dashboard:async()=>({visitsToday:2}),listeners:async()=>3},verifyIdToken:async()=>({uid:'admin'}),getAdminUid:()=> 'admin'});const r=res();await h(req('/api/admin/analytics',{Authorization:'Bearer fixture'}),r);assert.equal(r.code,200);const p=res();await h(req('/api/audience/listeners'),p);assert.deepEqual(p.body,{success:true,listeners:3});});
test('technical bot and cross-origin requests never produce writes',async()=>{let writes=0;const h=createAudience({repository:{track:async()=>writes++},clock:()=>now});for(const headers of [{Origin:'https://evil.example'},{Origin:'https://radar-acs.web.app','User-Agent':'healthcheck bot'}]){await h(req('/api/audience/event',headers,event()),res());}assert.equal(writes,0);});
test('audio daily aggregate records one consenting browser per day',()=>{const e=event('audio_start');let d=updateDaily(null,e,now).doc;assert.equal(updateDaily(d,event('audio_start'),now+60000).changed,false);assert.equal(d.audioSessions,1);});
