const test=require('node:test'),assert=require('node:assert/strict');
const {createCollector}=require('../api/editorial-collector');
const {defaultSettings}=require('../api/editorial-settings');
const config=require('../api/editorial-v2-config.json');
const prose='A equipe de desenvolvimento publicou nesta terça-feira ferramentas novas para os projetos de software. O anúncio explica recursos disponíveis para desenvolvedores e apresenta detalhes técnicos das ferramentas de software.';
const source=(id,category)=>({id,name:id,url:`https://${id}.example.org/`,categories:[category],quality:3,articlePattern:'^/news/.+'});
const article=(id)=>`<script type="application/ld+json">${JSON.stringify({'@type':'NewsArticle',headline:`Ferramentas de software para desenvolvimento ${id}`,datePublished:'2026-10-06',articleBody:prose})}</script>`;
const listing='<a href="/news/a">Ferramentas de software para desenvolvimento a</a><a href="/news/b">Ferramentas de software para desenvolvimento b</a>';
async function run(limits={},sources=[source('tech','tecnologiaIA')],fetcher){const urls=[];const result=await createCollector({sources,includeTeamSources:false,limits:{...config,...limits},fetchImpl:async url=>{urls.push(url);return fetcher?fetcher(url):{ok:true,status:200,text:async()=>new URL(url).pathname==='/'?listing:article(new URL(url).pathname)}}})({settings:defaultSettings(),date:'2026-10-06'});return {result,urls};}
test('progressive verification resolves pending metadata from article',async()=>{const {result}=await run();assert.ok(result.candidates.every(x=>x.verified&&x.dateStatus==='DATE_RESOLVED'&&x.evidenceStatus==='FULL_EVIDENCE'));});
test('configurable request budget preserves pending candidates',async()=>{const {result}=await run({maxExternalRequests:1});assert.equal(result.metrics.totalRequests,1);assert.equal(result.metrics.stoppedBecauseBudgetReached,true);assert.equal(result.candidates[0].dateStatus,'DATE_PENDING_VERIFICATION');assert.equal(result.candidates[0].evidenceStatus,'EVIDENCE_PENDING_VERIFICATION');});
test('stop at pool target avoids opening all discovered pages',async()=>{const {result}=await run({targetPoolMin:1});assert.equal(result.metrics.stoppedBecausePoolReady,true);assert.equal(result.metrics.articleVerificationRequests,1);});
test('per-source budget does not pretend unverified candidates were exhausted',async()=>{const {result}=await run({maxArticleVerificationsPerSource:1});assert.equal(result.metrics.articleVerificationRequests,1);assert.equal(result.metrics.stopReason,'SOURCE_VERIFICATION_LIMIT');assert.ok(result.candidates.some(x=>!x.verified));});
test('coverage-aware exploration visits another high category first',async()=>{const {urls}=await run({maxArticleFetches:2},[source('career','concursosCarreira'),source('tech','tecnologiaIA')]);const articleUrls=urls.filter(x=>new URL(x).pathname!=='/');assert.equal(new Set(articleUrls.map(x=>new URL(x).hostname)).size,2);});
test('blocked source is not retried and health is BLOCKED',async()=>{const {result,urls}=await run({},undefined,async()=>({ok:false,status:403}));assert.equal(urls.length,1);assert.equal(result.metrics.sourceHealth[0].status,'BLOCKED');});
test('discovery-only source remains observable without accepting listing',async()=>{const {result}=await run({},undefined,async()=>({ok:true,status:200,text:async()=>'<main><h1>Seção sem artigos</h1></main>'}));assert.equal(result.metrics.sourceHealth[0].status,'DISCOVERY_ONLY');assert.equal(result.candidates.length,0);});
test('feed date prioritization skips known old content',async()=>{const {result}=await run({},undefined,async()=>({ok:true,status:200,text:async()=>'<rss><channel><item><title>Ferramentas antigas</title><link>https://tech.example.org/news/old</link><pubDate>Mon, 01 Jun 2026 12:00:00 GMT</pubDate></item></channel></rss>'}));assert.equal(result.metrics.articleVerificationRequests,0);assert.equal(result.metrics.sourceHealth[0].status,'NO_RECENT_CONTENT');});
