import { test, expect } from '@playwright/test';
import fs from 'node:fs';
const { latest, live, ads } = JSON.parse(fs.readFileSync(new URL('./refinement-fixture.json', import.meta.url), 'utf8'));
for (const width of [375, 390, 430, 768, 1440, 1920]) test(`referência final: Ouvir, Home, foco e movimento em ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: 1000 });
  await page.route('**/api/radar/latest', route => route.fulfill({ json: latest }));
  await page.route('**/api/live', route => route.fulfill({ json: live }));
  await page.route('**/api/advertising', route => route.fulfill({ json: ads }));
  await page.route('https://acstech.dev.br/**', route => route.fulfill({ contentType: 'image/png', body: fs.readFileSync(new URL('../public/logo-acs.png', import.meta.url)) }));
  await page.route('https://yt3.googleusercontent.com/**', route => route.abort());
  await page.route('https://open.spotify.com/embed/**', route => route.fulfill({ contentType: 'text/html', body: '<!doctype html><title>Widget técnico local</title>' }));
  await page.goto('/listen');
  await expect(page.locator('.listen-hero-photo')).toBeVisible();
  expect(await page.locator('.listen-hero-photo').evaluate(img => img.complete && img.naturalWidth > 0)).toBe(true);
  await expect(page.getByRole('heading', { name: 'Jovem Pan News', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'ACS Music', exact: true })).toBeVisible();
  await expect(page.locator('.media-featured')).toHaveCount(2);
  await expect(page.locator('.news-item')).toHaveCount(latest.briefing.noticias.length);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('button', { name: 'Player não carregou?' }).click();
  await expect(page.locator('iframe')).toHaveCount(0);
  await expect(page.getByText('Ouça esta playlist no Spotify.')).toBeVisible();
  await page.goto('/');
  await expect(page.locator('.ad-slot-home_top')).toBeVisible();
  const ad = await page.locator('.ad-slot-home_top').boundingBox();
  if (width < 768) expect(ad.height).toBeLessThan(220);
  await expect(page.locator('.home-editorial-layout .news-lead')).toHaveCount(1);
  await page.emulateMedia({ reducedMotion: 'reduce' });
  expect(await page.locator('.radar-sweep').first().evaluate(node => getComputedStyle(node).animationName)).toBe('none');
  await page.getByRole('button', { name: 'Ler edição', exact: true }).click();
  await page.keyboard.press('Tab');
  expect(await page.getByRole('dialog').evaluate(node => node.contains(document.activeElement))).toBe(true);
  await page.keyboard.press('Escape');
  await expect(page.getByRole('button', { name: 'Ler edição', exact: true })).toBeFocused();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
